//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ping_2020.AuthorityService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="authorityServiceSoap11Binding", Namespace="www.seeyon.com")]
    public partial class authorityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authenticateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public authorityService() {
            this.Url = global::ping_2020.Properties.Settings.Default.ping_2020_WebReference_authorityService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authenticateCompletedEventHandler authenticateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:authenticate", RequestNamespace="http://impl.services.v3x.seeyon.com", ResponseNamespace="http://impl.services.v3x.seeyon.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public UserToken authenticate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            object[] results = this.Invoke("authenticate", new object[] {
                        userName,
                        password});
            return ((UserToken)(results[0]));
        }
        
        /// <remarks/>
        public void authenticateAsync(string userName, string password) {
            this.authenticateAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void authenticateAsync(string userName, string password, object userState) {
            if ((this.authenticateOperationCompleted == null)) {
                this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
            }
            this.InvokeAsync("authenticate", new object[] {
                        userName,
                        password}, this.authenticateOperationCompleted, userState);
        }
        
        private void OnauthenticateOperationCompleted(object arg) {
            if ((this.authenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ctp.seeyon.com/xsd")]
    public partial class UserToken {
        
        private User bindingUserField;
        
        private string idField;
        
        private UserToken nullTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public User bindingUser {
            get {
                return this.bindingUserField;
            }
            set {
                this.bindingUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserToken nullToken {
            get {
                return this.nullTokenField;
            }
            set {
                this.nullTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.authenticate.common.ctp.seeyon.com/xsd")]
    public partial class User {
        
        private Set accessSystemMenuField;
        
        private System.Nullable<long> accountIdField;
        
        private bool accountIdFieldSpecified;
        
        private bool adminField;
        
        private bool adminFieldSpecified;
        
        private bool administratorField;
        
        private bool administratorFieldSpecified;
        
        private bool auditAdminField;
        
        private bool auditAdminFieldSpecified;
        
        private BrowserEnum browserField;
        
        private bool canSendSMSField;
        
        private bool canSendSMSFieldSpecified;
        
        private Map customizesField;
        
        private System.Nullable<long> departmentIdField;
        
        private bool departmentIdFieldSpecified;
        
        private string etagRandomField;
        
        private System.Nullable<int> externalTypeField;
        
        private bool externalTypeFieldSpecified;
        
        private string fontSizeField;
        
        private bool fromM1Field;
        
        private bool fromM1FieldSpecified;
        
        private bool groupAdminField;
        
        private bool groupAdminFieldSpecified;
        
        private System.Nullable<long> idField;
        
        private bool idFieldSpecified;
        
        private bool internalField;
        
        private bool internalFieldSpecified;
        
        private System.Nullable<long> levelIdField;
        
        private bool levelIdFieldSpecified;
        
        private Locale localeField;
        
        private System.Nullable<long> loginAccountField;
        
        private bool loginAccountFieldSpecified;
        
        private string loginAccountNameField;
        
        private string loginAccountShortNameField;
        
        private System.Nullable<long> loginLogIdField;
        
        private bool loginLogIdFieldSpecified;
        
        private string loginNameField;
        
        private int loginSignField;
        
        private bool loginSignFieldSpecified;
        
        private User_login_state_enum loginStateField;
        
        private long loginTimestampField;
        
        private bool loginTimestampFieldSpecified;
        
        private string mainFrameField;
        
        private string nameField;
        
        private string passwordField;
        
        private bool platformAdminField;
        
        private bool platformAdminFieldSpecified;
        
        private System.Nullable<long> postIdField;
        
        private bool postIdFieldSpecified;
        
        private string remoteAddrField;
        
        private string resourceJsonStrField;
        
        private long securityKeyField;
        
        private bool securityKeyFieldSpecified;
        
        private string sessionIdField;
        
        private string skinField;
        
        private bool superAdminField;
        
        private bool superAdminFieldSpecified;
        
        private bool systemAdminField;
        
        private bool systemAdminFieldSpecified;
        
        private TimeZone timeZoneField;
        
        private string userAgentFromField;
        
        private Constants_login_useragent_from userAgentFromEnumField;
        
        private string userInfoJsonStrField;
        
        private string userSSOFromField;
        
        private bool v5MemberField;
        
        private bool v5MemberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set accessSystemMenu {
            get {
                return this.accessSystemMenuField;
            }
            set {
                this.accessSystemMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountIdSpecified {
            get {
                return this.accountIdFieldSpecified;
            }
            set {
                this.accountIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adminSpecified {
            get {
                return this.adminFieldSpecified;
            }
            set {
                this.adminFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool administrator {
            get {
                return this.administratorField;
            }
            set {
                this.administratorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool administratorSpecified {
            get {
                return this.administratorFieldSpecified;
            }
            set {
                this.administratorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool auditAdmin {
            get {
                return this.auditAdminField;
            }
            set {
                this.auditAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool auditAdminSpecified {
            get {
                return this.auditAdminFieldSpecified;
            }
            set {
                this.auditAdminFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BrowserEnum browser {
            get {
                return this.browserField;
            }
            set {
                this.browserField = value;
            }
        }
        
        /// <remarks/>
        public bool canSendSMS {
            get {
                return this.canSendSMSField;
            }
            set {
                this.canSendSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canSendSMSSpecified {
            get {
                return this.canSendSMSFieldSpecified;
            }
            set {
                this.canSendSMSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Map customizes {
            get {
                return this.customizesField;
            }
            set {
                this.customizesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> departmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departmentIdSpecified {
            get {
                return this.departmentIdFieldSpecified;
            }
            set {
                this.departmentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string etagRandom {
            get {
                return this.etagRandomField;
            }
            set {
                this.etagRandomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> externalType {
            get {
                return this.externalTypeField;
            }
            set {
                this.externalTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool externalTypeSpecified {
            get {
                return this.externalTypeFieldSpecified;
            }
            set {
                this.externalTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
        
        /// <remarks/>
        public bool fromM1 {
            get {
                return this.fromM1Field;
            }
            set {
                this.fromM1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromM1Specified {
            get {
                return this.fromM1FieldSpecified;
            }
            set {
                this.fromM1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool groupAdmin {
            get {
                return this.groupAdminField;
            }
            set {
                this.groupAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupAdminSpecified {
            get {
                return this.groupAdminFieldSpecified;
            }
            set {
                this.groupAdminFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool @internal {
            get {
                return this.internalField;
            }
            set {
                this.internalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool internalSpecified {
            get {
                return this.internalFieldSpecified;
            }
            set {
                this.internalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> levelId {
            get {
                return this.levelIdField;
            }
            set {
                this.levelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelIdSpecified {
            get {
                return this.levelIdFieldSpecified;
            }
            set {
                this.levelIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Locale locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> loginAccount {
            get {
                return this.loginAccountField;
            }
            set {
                this.loginAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginAccountSpecified {
            get {
                return this.loginAccountFieldSpecified;
            }
            set {
                this.loginAccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginAccountName {
            get {
                return this.loginAccountNameField;
            }
            set {
                this.loginAccountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginAccountShortName {
            get {
                return this.loginAccountShortNameField;
            }
            set {
                this.loginAccountShortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> loginLogId {
            get {
                return this.loginLogIdField;
            }
            set {
                this.loginLogIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginLogIdSpecified {
            get {
                return this.loginLogIdFieldSpecified;
            }
            set {
                this.loginLogIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public int loginSign {
            get {
                return this.loginSignField;
            }
            set {
                this.loginSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginSignSpecified {
            get {
                return this.loginSignFieldSpecified;
            }
            set {
                this.loginSignFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public User_login_state_enum loginState {
            get {
                return this.loginStateField;
            }
            set {
                this.loginStateField = value;
            }
        }
        
        /// <remarks/>
        public long loginTimestamp {
            get {
                return this.loginTimestampField;
            }
            set {
                this.loginTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginTimestampSpecified {
            get {
                return this.loginTimestampFieldSpecified;
            }
            set {
                this.loginTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mainFrame {
            get {
                return this.mainFrameField;
            }
            set {
                this.mainFrameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool platformAdmin {
            get {
                return this.platformAdminField;
            }
            set {
                this.platformAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool platformAdminSpecified {
            get {
                return this.platformAdminFieldSpecified;
            }
            set {
                this.platformAdminFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> postId {
            get {
                return this.postIdField;
            }
            set {
                this.postIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postIdSpecified {
            get {
                return this.postIdFieldSpecified;
            }
            set {
                this.postIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remoteAddr {
            get {
                return this.remoteAddrField;
            }
            set {
                this.remoteAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resourceJsonStr {
            get {
                return this.resourceJsonStrField;
            }
            set {
                this.resourceJsonStrField = value;
            }
        }
        
        /// <remarks/>
        public long securityKey {
            get {
                return this.securityKeyField;
            }
            set {
                this.securityKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool securityKeySpecified {
            get {
                return this.securityKeyFieldSpecified;
            }
            set {
                this.securityKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string skin {
            get {
                return this.skinField;
            }
            set {
                this.skinField = value;
            }
        }
        
        /// <remarks/>
        public bool superAdmin {
            get {
                return this.superAdminField;
            }
            set {
                this.superAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool superAdminSpecified {
            get {
                return this.superAdminFieldSpecified;
            }
            set {
                this.superAdminFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool systemAdmin {
            get {
                return this.systemAdminField;
            }
            set {
                this.systemAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool systemAdminSpecified {
            get {
                return this.systemAdminFieldSpecified;
            }
            set {
                this.systemAdminFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TimeZone timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userAgentFrom {
            get {
                return this.userAgentFromField;
            }
            set {
                this.userAgentFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Constants_login_useragent_from userAgentFromEnum {
            get {
                return this.userAgentFromEnumField;
            }
            set {
                this.userAgentFromEnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfoJsonStr {
            get {
                return this.userInfoJsonStrField;
            }
            set {
                this.userInfoJsonStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userSSOFrom {
            get {
                return this.userSSOFromField;
            }
            set {
                this.userSSOFromField = value;
            }
        }
        
        /// <remarks/>
        public bool v5Member {
            get {
                return this.v5MemberField;
            }
            set {
                this.v5MemberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool v5MemberSpecified {
            get {
                return this.v5MemberFieldSpecified;
            }
            set {
                this.v5MemberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://util.java/xsd")]
    public partial class Set {
        
        private bool emptyField;
        
        private bool emptyFieldSpecified;
        
        /// <remarks/>
        public bool empty {
            get {
                return this.emptyField;
            }
            set {
                this.emptyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emptySpecified {
            get {
                return this.emptyFieldSpecified;
            }
            set {
                this.emptyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://constants.common.ctp.seeyon.com/xsd")]
    public partial class Constants_login_useragent_from {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://util.java/xsd")]
    public partial class TimeZone {
        
        private string[] availableIDsField;
        
        private int dSTSavingsField;
        
        private bool dSTSavingsFieldSpecified;
        
        private TimeZone defaultField;
        
        private TimeZone defaultRefField;
        
        private string displayNameField;
        
        private string idField;
        
        private int rawOffsetField;
        
        private bool rawOffsetFieldSpecified;
        
        private string systemGMTOffsetIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availableIDs", IsNullable=true)]
        public string[] availableIDs {
            get {
                return this.availableIDsField;
            }
            set {
                this.availableIDsField = value;
            }
        }
        
        /// <remarks/>
        public int dSTSavings {
            get {
                return this.dSTSavingsField;
            }
            set {
                this.dSTSavingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dSTSavingsSpecified {
            get {
                return this.dSTSavingsFieldSpecified;
            }
            set {
                this.dSTSavingsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TimeZone @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TimeZone defaultRef {
            get {
                return this.defaultRefField;
            }
            set {
                this.defaultRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string iD {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int rawOffset {
            get {
                return this.rawOffsetField;
            }
            set {
                this.rawOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rawOffsetSpecified {
            get {
                return this.rawOffsetFieldSpecified;
            }
            set {
                this.rawOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string systemGMTOffsetID {
            get {
                return this.systemGMTOffsetIDField;
            }
            set {
                this.systemGMTOffsetIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.authenticate.common.ctp.seeyon.com/xsd")]
    public partial class User_login_state_enum {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://locale.util.sun/xsd")]
    public partial class LocaleExtensions {
        
        private bool emptyField;
        
        private bool emptyFieldSpecified;
        
        private string idField;
        
        private Set keysField;
        
        private Set unicodeLocaleAttributesField;
        
        private Set unicodeLocaleKeysField;
        
        /// <remarks/>
        public bool empty {
            get {
                return this.emptyField;
            }
            set {
                this.emptyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emptySpecified {
            get {
                return this.emptyFieldSpecified;
            }
            set {
                this.emptyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string iD {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set unicodeLocaleAttributes {
            get {
                return this.unicodeLocaleAttributesField;
            }
            set {
                this.unicodeLocaleAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set unicodeLocaleKeys {
            get {
                return this.unicodeLocaleKeysField;
            }
            set {
                this.unicodeLocaleKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://locale.util.sun/xsd")]
    public partial class BaseLocale {
        
        private string languageField;
        
        private string regionField;
        
        private string scriptField;
        
        private string variantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://util.java/xsd")]
    public partial class Locale {
        
        private Locale[] availableLocalesField;
        
        private BaseLocale baseLocaleField;
        
        private string countryField;
        
        private Locale defaultField;
        
        private string displayCountryField;
        
        private string displayLanguageField;
        
        private string displayNameField;
        
        private string displayScriptField;
        
        private string displayVariantField;
        
        private Set extensionKeysField;
        
        private string iSO3CountryField;
        
        private string iSO3LanguageField;
        
        private string[] iSOCountriesField;
        
        private string[] iSOLanguagesField;
        
        private string languageField;
        
        private LocaleExtensions localeExtensionsField;
        
        private string scriptField;
        
        private Set unicodeLocaleAttributesField;
        
        private Set unicodeLocaleKeysField;
        
        private string variantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availableLocales", IsNullable=true)]
        public Locale[] availableLocales {
            get {
                return this.availableLocalesField;
            }
            set {
                this.availableLocalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BaseLocale baseLocale {
            get {
                return this.baseLocaleField;
            }
            set {
                this.baseLocaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Locale @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayCountry {
            get {
                return this.displayCountryField;
            }
            set {
                this.displayCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayLanguage {
            get {
                return this.displayLanguageField;
            }
            set {
                this.displayLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayScript {
            get {
                return this.displayScriptField;
            }
            set {
                this.displayScriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayVariant {
            get {
                return this.displayVariantField;
            }
            set {
                this.displayVariantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set extensionKeys {
            get {
                return this.extensionKeysField;
            }
            set {
                this.extensionKeysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string iSO3Country {
            get {
                return this.iSO3CountryField;
            }
            set {
                this.iSO3CountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string iSO3Language {
            get {
                return this.iSO3LanguageField;
            }
            set {
                this.iSO3LanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("iSOCountries", IsNullable=true)]
        public string[] iSOCountries {
            get {
                return this.iSOCountriesField;
            }
            set {
                this.iSOCountriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("iSOLanguages", IsNullable=true)]
        public string[] iSOLanguages {
            get {
                return this.iSOLanguagesField;
            }
            set {
                this.iSOLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LocaleExtensions localeExtensions {
            get {
                return this.localeExtensionsField;
            }
            set {
                this.localeExtensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set unicodeLocaleAttributes {
            get {
                return this.unicodeLocaleAttributesField;
            }
            set {
                this.unicodeLocaleAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Set unicodeLocaleKeys {
            get {
                return this.unicodeLocaleKeysField;
            }
            set {
                this.unicodeLocaleKeysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://util.java/xsd")]
    public partial class Map {
        
        private bool emptyField;
        
        private bool emptyFieldSpecified;
        
        /// <remarks/>
        public bool empty {
            get {
                return this.emptyField;
            }
            set {
                this.emptyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emptySpecified {
            get {
                return this.emptyFieldSpecified;
            }
            set {
                this.emptyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flag.common.ctp.seeyon.com/xsd")]
    public partial class BrowserEnum {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserToken)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591